name: ASP.NET Core

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  FUNCTIONAPP_NAME: functionappfromghactions
  FUNCTIONAPP_PACKAGE_PATH: './publish'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test with coverage
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: dotnet publish -c Release -o "./publish"
      - name: Archive publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: './publish'
          
  deploy:

    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: publish
      
      - name: Publish Azure Function
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCTIONAPP_NAME }}
          package: './publish'
          publish-profile: ${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE }}
    
    